{% set version = "1.6.3" %}

package:
  name: geoviews-core
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/geoviews/geoviews-{{ version }}.tar.gz
  sha256: 5db961570e4dfe15c93505c176eceffa2086c5547cac43fd9c14b3281a26d5fe

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - geoviews = geoviews.__main__:main

requirements:
  run_constrained:
    - geoviews {{ version }}
  host:
    - python
    - pip
    - param >=1.6.1,<2.0
  run:
    - python >=2.7
    - bokeh >=0.12.15
    - cartopy >=0.14.2
    - holoviews >=1.10.1
    - numpy >=1.0
    - param >=1.6.1,<2.0

test:
  imports:
    - geoviews
  requires:
    - nose
  commands:
    - nosetests geoviews

about:
  home: https://geoviews.org
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: GeoViews is a Python library that makes it easy to explore and visualize
        geographical, meteorological, and oceanographic datasets, such as those used
        in weather, climate, and remote sensing research.

extra:
  recipe-maintainers:
    - ocefpaf
    - philippjfr
